// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKz1k3s88ptN4YgTRdYZpjLvj_IAcM6Gg',
    appId: '1:1080213487625:web:b2340b0c9ffebddda878d8',
    messagingSenderId: '1080213487625',
    projectId: 'smart-habitat-a0f8a',
    authDomain: 'smart-habitat-a0f8a.firebaseapp.com',
    databaseURL: 'https://smart-habitat-a0f8a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-habitat-a0f8a.firebasestorage.app',
    measurementId: 'G-E96ZMW9FBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8QSrkWMHpON6nGRMbIjOyX2mb492Xrd8',
    appId: '1:1080213487625:android:aaa39e0b8deb7feda878d8',
    messagingSenderId: '1080213487625',
    projectId: 'smart-habitat-a0f8a',
    databaseURL: 'https://smart-habitat-a0f8a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-habitat-a0f8a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKz1k3s88ptN4YgTRdYZpjLvj_IAcM6Gg',
    appId: '1:1080213487625:web:4bd03d7a510eb2baa878d8',
    messagingSenderId: '1080213487625',
    projectId: 'smart-habitat-a0f8a',
    authDomain: 'smart-habitat-a0f8a.firebaseapp.com',
    databaseURL: 'https://smart-habitat-a0f8a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-habitat-a0f8a.firebasestorage.app',
    measurementId: 'G-EZYJN53SM3',
  );
}
